services:
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: postgres
    environment:
      POSTGRES_DB: "gophstream"
      POSTGRES_USER: "gophstream"
      POSTGRES_PASSWORD: "example"
    ports:
      - "5432:5432"
    networks:
      - priceanalyzer_network
 
networks:
  priceanalyzer_network:
    driver: bridge
